### PR TITLE
Update 2023-10-hpc-on-boarding.md - unifying format of exercise text

### PR DESCRIPTION
**Pull request by maikenp**

### CODE REVIEW

**Comment by bast** [comment]
Can you please apply the change on GitLab? This is only the mirror. Otherwise I need to apply it there also.

**Comment by maikenp** [comment]
Ah, yes, sure

From: Radovan Bast ***@***.***>
Reply to: UNINETTSigma2/documentation ***@***.***>
Date: Monday, 25 September 2023 at 11:24
To: UNINETTSigma2/documentation ***@***.***>
Cc: Maiken Pedersen ***@***.***>, Author ***@***.***>
Subject: Re: [UNINETTSigma2/documentation] Update 2023-10-hpc-on-boarding.md - unifying format of exercise text (PR #14)


Can you please apply the change on GitLab? This is only the mirror. Otherwise I need to apply it there also.

**Comment by maikenp** [comment]
There was this handy «Edit on GitHub” button there, so that is why I assumed that was the right place.

This is clearly not the right repo https://gitlab.sigma2.no/training/training-events
How do I go about finding out which repo the page https://documentation.sigma2.no/training/events/2023-10-hpc-on-boarding.html is built on?

Maiken

From: Radovan Bast ***@***.***>
Reply to: UNINETTSigma2/documentation ***@***.***>
Date: Monday, 25 September 2023 at 11:24
To: UNINETTSigma2/documentation ***@***.***>
Cc: Maiken Pedersen ***@***.***>, Author ***@***.***>
Subject: Re: [UNINETTSigma2/documentation] Update 2023-10-hpc-on-boarding.md - unifying format of exercise text (PR #14)


Can you please apply the change on GitLab? This is only the mirror. Otherwise I need to apply it there also.

**Comment by bast** [comment]
About the button: The question is whether we make it more useful for staff or more useful for external contributors.

Here is the repo: https://gitlab.sigma2.no/documentation/public/ - and maybe this should also go into the README.

**Comment by bast** [comment]
Closing. Applied through GitLab. Thanks and sorry for the detour.

**Pull request closed without merging**
